---
language: node_js
node_js:
  - "4"

sudo: true
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  # Locking to Yarn 1.0.2 to work around https://github.com/yarnpkg/yarn/issues/4612
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

# script:
#   - yarn lint:js
#   # We need to cleanup, since our deploy depends on the git repo's status
#   - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  email: false

stages:
  - test
  - additional tests
  - versioned tests
  - deploy

jobs:
  fail_fast: true

  include:
    - stage: test
      env: NAME=test
      script: yarn test

    - stage: additional tests
      env: NAME=floating dependencies
      install: yarn install --no-lockfile --non-interactive
      script: yarn test

    - stage: versioned tests
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default

    - stage: deploy
      if: (branch = master OR tag IS present) AND type = push
      env: NAME=deploy
      script: node_modules/.bin/ember deploy production
